import Foundation

enum EffectCategory: String, CaseIterable, Identifiable {
    case geometry = "Geometry", light = "Light", particles = "Particles", rhythm = "Rhythm", distortion = "Distortion", masks = "Masks", interfaces = "UI Playground", systems = "Nerd Lab"
    var id: String { rawValue }
    var symbol: String {
        switch self {
        case .geometry: "hexagon"
        case .light: "sun.max"
        case .particles: "sparkles"
        case .rhythm: "waveform.path"
        case .distortion: "camera.filters"
        case .masks: "square.stack.3d.up.fill"
        case .interfaces: "slider.horizontal.3"
        case .systems: "terminal"
        }
    }
}

enum ArtEffect: Int, CaseIterable, Identifiable, Sendable {
    case orbit, tunnel, spiral, mandala, lattice, moire, radar, diamonds, starburst, hexagons
    case prism, ribbons, aurora, neonRain, laserSweep, lightning, bokeh, comet, fireflies, confetti
    case sparks, snowfall, bubbles, meteors, starfield, fire, embers, fountain, constellation, vortex
    case pulse, blink, checker, shutter, scanlines, equalizer, interference, heartbeat, eclipse, clear
    case kaleidoscope, mirrorTiles, ripple, twirl, bulge, pixelate, rgbSplit, negative, solarize, posterize

    case colorCurtains, inkBlobs, mosaic, iris, wipes, solidWaves, paperCut, checkerBlocks, petalShutter, liquidIslands

    case sliderStack, toggleRain, buttonStorm, terminal, codeRain, debugHUD, progressMaze, permissionStack, syntaxGarden, breakpointGrid
    case memoryHeap, packetRouter, taskQueue, inspector, buildLog, rainbowPicker, gaugeCluster, consoleWall, windowCascade, fatalError

    var id: Int { rawValue }
    var category: EffectCategory { EffectCategory.allCases[rawValue / 10] }
    var processesCamera: Bool { category == .distortion }
    var name: String {
        switch self {
        case .colorCurtains: "Color Curtains"
        case .inkBlobs: "Ink Flood"
        case .mosaic: "Opaque Mosaic"
        case .iris: "Iris Window"
        case .wipes: "Crossing Walls"
        case .solidWaves: "Solid Tides"
        case .paperCut: "Paper Cutouts"
        case .checkerBlocks: "Block Party"
        case .petalShutter: "Petal Shutter"
        case .liquidIslands: "Liquid Islands"
        case .sliderStack: "Slider Synth"
        case .toggleRain: "Toggle Rain"
        case .buttonStorm: "Button Storm"
        case .terminal: "Tiny Terminal"
        case .codeRain: "Code Rain"
        case .debugHUD: "Debug HUD"
        case .progressMaze: "Progress Paradox"
        case .permissionStack: "Permission Party"
        case .syntaxGarden: "Syntax Garden"
        case .breakpointGrid: "Breakpoint Disco"
        case .memoryHeap: "Memory Heap"
        case .packetRouter: "Packet Router"
        case .taskQueue: "Task Orchestra"
        case .inspector: "Inspector Gadget"
        case .buildLog: "Build Forever"
        case .rainbowPicker: "Rainbow Picker"
        case .gaugeCluster: "Gauge Reactor"
        case .consoleWall: "Console Wall"
        case .windowCascade: "Window Cascade"
        case .fatalError: "Friendly Fatal Error"
        case .orbit: "Orbit"
        case .tunnel: "Tunnel"
        case .spiral: "Spiral Ink"
        case .mandala: "Mandala"
        case .lattice: "Liquid Grid"
        case .moire: "Moiré"
        case .radar: "Radar"
        case .diamonds: "Diamond Drift"
        case .starburst: "Starburst"
        case .hexagons: "Honeycomb"
        case .prism: "Prism"
        case .ribbons: "Ribbons"
        case .aurora: "Aurora"
        case .neonRain: "Neon Rain"
        case .laserSweep: "Laser Sweep"
        case .lightning: "Lightning"
        case .bokeh: "Bokeh"
        case .comet: "Comet Trails"
        case .fireflies: "Fireflies"
        case .confetti: "Confetti"
        case .sparks: "Sparks"
        case .snowfall: "Snowfall"
        case .bubbles: "Bubbles"
        case .meteors: "Meteor Shower"
        case .starfield: "Warp Speed"
        case .fire: "Flame Garden"
        case .embers: "Embers"
        case .fountain: "Fountain"
        case .constellation: "Constellations"
        case .vortex: "Vortex"
        case .pulse: "Color Breath"
        case .blink: "Blink"
        case .checker: "Checker Dance"
        case .shutter: "Venetian Shutter"
        case .scanlines: "CRT Scan"
        case .equalizer: "Electric Bars"
        case .interference: "Interference"
        case .heartbeat: "Heartbeat"
        case .eclipse: "Eclipse"
        case .clear: "Clear"
        case .kaleidoscope: "Kaleidoscope"
        case .mirrorTiles: "Mirror Tiles"
        case .ripple: "Liquid Lens"
        case .twirl: "Twirl"
        case .bulge: "Breathing Lens"
        case .pixelate: "Pixel Melt"
        case .rgbSplit: "Chromatic Ghost"
        case .negative: "Negative"
        case .solarize: "Solar Flare"
        case .posterize: "Pop Art"
        }
    }

    var detail: String {
        switch self {
        case .colorCurtains: "Opaque curtains open narrow camera slits"
        case .inkBlobs: "Large ink pools drift over the image"
        case .mosaic: "Solid colored tiles with moving gaps"
        case .iris: "A moving circular window into the camera"
        case .wipes: "Broad walls sweep across each other"
        case .solidWaves: "Solid waves cover most of the lower frame"
        case .paperCut: "Tumbling oversized pieces of colored paper"
        case .checkerBlocks: "Thick rotating blocks conceal the scene"
        case .petalShutter: "Opaque petals close around the center"
        case .liquidIslands: "A colored field with drifting camera windows"
        case .sliderStack: "A mixer of animated SwiftUI sliders"
        case .toggleRain: "A wall of switches with a mind of its own"
        case .buttonStorm: "Floating buttons that refuse to sit still"
        case .terminal: "A terminal inventing recursive commands"
        case .codeRain: "Columns of falling Swift fragments"
        case .debugHUD: "A moving heads-up display of imaginary metrics"
        case .progressMaze: "Nested progress bars that never quite finish"
        case .permissionStack: "Stacked absurd permission dialogs"
        case .syntaxGarden: "Orbiting colored Swift syntax"
        case .breakpointGrid: "A grid of pulsing breakpoint buttons"
        case .memoryHeap: "Memory blocks allocate and release in waves"
        case .packetRouter: "Packets travel between imaginary network nodes"
        case .taskQueue: "Concurrent jobs compete for progress"
        case .inspector: "A property inspector for the universe"
        case .buildLog: "An endless fictional compiler transcript"
        case .rainbowPicker: "Segmented pickers cycle through impossible palettes"
        case .gaugeCluster: "A reactor made of animated SwiftUI gauges"
        case .consoleWall: "Scrolling fake logs multiply across the frame"
        case .windowCascade: "Overlapping toy desktop windows"
        case .fatalError: "A cheerful crash card with an animated recovery meter"
        case .orbit: "Five wandering neon rings"
        case .tunnel: "Rotating portals expanding outward"
        case .spiral: "A rainbow spiral drawing itself"
        case .mandala: "Petals in a turning geometric bloom"
        case .lattice: "A grid that bends like water"
        case .moire: "Two drifting fields of fine lines"
        case .radar: "A luminous circular sweep"
        case .diamonds: "Floating, tumbling outlines"
        case .starburst: "Rays radiating from a moving sun"
        case .hexagons: "A breathing honeycomb mesh"
        case .prism: "Three overlapping pools of color"
        case .ribbons: "Six silky waves across the frame"
        case .aurora: "Luminous curtains of polar light"
        case .neonRain: "Falling columns of colored dashes"
        case .laserSweep: "Crossing beams of light"
        case .lightning: "Branching bolts that flicker briefly"
        case .bokeh: "Soft, drifting discs of light"
        case .comet: "Orbiting heads with fading tails"
        case .fireflies: "Tiny lights blinking independently"
        case .confetti: "Rotating scraps of color"
        case .sparks: "Rising multicolor points"
        case .snowfall: "White flakes drifting sideways"
        case .bubbles: "Iridescent rings floating upward"
        case .meteors: "Diagonal streaks across the sky"
        case .starfield: "Stars accelerating toward you"
        case .fire: "Wavering tongues of warm light"
        case .embers: "Orange motes rising from below"
        case .fountain: "Particles following falling arcs"
        case .constellation: "Moving stars joined by fine threads"
        case .vortex: "Particles spiraling into the center"
        case .pulse: "A slow wash of breathing color"
        case .blink: "Alternating colored corner lights"
        case .checker: "A shifting translucent chessboard"
        case .shutter: "Dark slats opening and closing"
        case .scanlines: "Fine scan lines and a rolling beam"
        case .equalizer: "Animated bars on a synthetic beat"
        case .interference: "Crossing waves of luminous dots"
        case .heartbeat: "An electric trace with expanding echoes"
        case .eclipse: "A dark moon crossing a colored halo"
        case .clear: "No artwork; feedback color remains adjustable"
        case .kaleidoscope: "Six rotating reflected camera wedges"
        case .mirrorTiles: "The camera folded into mirrored tiles"
        case .ripple: "A moving glassy distortion in the image"
        case .twirl: "The center of the camera twists"
        case .bulge: "A lens that expands and contracts"
        case .pixelate: "Camera pixels swell and shrink"
        case .rgbSplit: "Color channels drift apart"
        case .negative: "Inverted camera colors"
        case .solarize: "Luminous, surreal tone reversals"
        case .posterize: "Bold camera colors in flat steps"
        }
    }

    func next(_ offset: Int) -> Self {
        let count = Self.allCases.count
        return Self(rawValue: ((rawValue + offset) % count + count) % count)!
    }
}
